import { SKILL_CATEGORIES, SKILL_LEVELS } from "@/lib/constants";
import type { CollectionConfig, FieldDef } from "@/types";

const commonToggles: FieldDef[] = [
  { name: "published", label: "Published", type: "checkbox" },
  { name: "featured", label: "Featured", type: "checkbox" },
];

export const COLLECTION_CONFIG: Record<string, CollectionConfig> = {
  experience: {
    key: "experience",
    title: "Experience",
    singular: "Role",
    description: "Positions, contracts, and professional history.",
    fields: [
      { name: "title", label: "Role title", type: "text", required: true },
      { name: "organization", label: "Company", type: "text", required: true },
      { name: "employmentType", label: "Employment type", type: "text", placeholder: "Full-time" },
      { name: "location", label: "Location", type: "text" },
      { name: "startDate", label: "Start", type: "date" },
      { name: "endDate", label: "End", type: "date" },
      { name: "current", label: "Current role", type: "checkbox" },
      { name: "description", label: "Summary", type: "textarea" },
      { name: "highlights", label: "Highlights", type: "tags", placeholder: "Shipped X, led Y" },
      { name: "url", label: "Company URL", type: "url" },
      { name: "imageUrl", label: "Logo", type: "image" },
      ...commonToggles,
    ],
  },
  education: {
    key: "education",
    title: "Education",
    singular: "School",
    description: "Degrees, coursework, and academic background.",
    fields: [
      { name: "title", label: "School / program", type: "text", required: true },
      { name: "organization", label: "Institution", type: "text" },
      { name: "degree", label: "Degree", type: "text" },
      { name: "field", label: "Field of study", type: "text" },
      { name: "location", label: "Location", type: "text" },
      { name: "startDate", label: "Start", type: "date" },
      { name: "endDate", label: "End", type: "date" },
      { name: "current", label: "In progress", type: "checkbox" },
      { name: "description", label: "Notes", type: "textarea" },
      { name: "url", label: "URL", type: "url" },
      { name: "imageUrl", label: "Logo", type: "image" },
      ...commonToggles,
    ],
  },
  affiliations: {
    key: "affiliations",
    title: "Affiliations",
    singular: "Affiliation",
    description: "Professional memberships, orgs, and communities.",
    fields: [
      { name: "title", label: "Organization", type: "text", required: true },
      { name: "role", label: "Role / membership", type: "text" },
      { name: "location", label: "Location", type: "text" },
      { name: "startDate", label: "Start", type: "date" },
      { name: "endDate", label: "End", type: "date" },
      { name: "current", label: "Current", type: "checkbox" },
      { name: "description", label: "Notes", type: "textarea" },
      { name: "url", label: "URL", type: "url" },
      { name: "imageUrl", label: "Logo", type: "image" },
      ...commonToggles,
    ],
  },
  certificates: {
    key: "certificates",
    title: "Certificates",
    singular: "Certificate",
    description: "Credentials, exams, and issued certificates.",
    fields: [
      { name: "title", label: "Certificate", type: "text", required: true },
      { name: "issuer", label: "Issuer", type: "text" },
      { name: "issueDate", label: "Issued", type: "date" },
      { name: "expiryDate", label: "Expires", type: "date" },
      { name: "credentialId", label: "Credential ID", type: "text" },
      { name: "credentialUrl", label: "Credential URL", type: "url" },
      { name: "description", label: "Notes", type: "textarea" },
      { name: "imageUrl", label: "Badge / image", type: "image" },
      { name: "fileUrl", label: "PDF / file", type: "image" },
      ...commonToggles,
    ],
  },
  trainings: {
    key: "trainings",
    title: "Trainings",
    singular: "Training",
    description: "Courses, bootcamps, and workshops.",
    fields: [
      { name: "title", label: "Training", type: "text", required: true },
      { name: "provider", label: "Provider", type: "text" },
      { name: "startDate", label: "Start", type: "date" },
      { name: "endDate", label: "End", type: "date" },
      { name: "hours", label: "Hours", type: "number" },
      { name: "description", label: "Notes", type: "textarea" },
      { name: "url", label: "URL", type: "url" },
      { name: "imageUrl", label: "Image", type: "image" },
      ...commonToggles,
    ],
  },
  projects: {
    key: "projects",
    title: "Projects",
    singular: "Project",
    description: "Case studies and shipped work.",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", placeholder: "auto from title if empty" },
      { name: "summary", label: "Short summary", type: "textarea" },
      { name: "description", label: "Case study (markdown)", type: "markdown" },
      { name: "stack", label: "Stack", type: "tags", placeholder: "React, MongoDB, Node" },
      { name: "repoUrl", label: "Repo URL", type: "url" },
      { name: "liveUrl", label: "Live URL", type: "url" },
      { name: "coverUrl", label: "Cover image", type: "image" },
      ...commonToggles,
    ],
  },
  skills: {
    key: "skills",
    title: "Skills",
    singular: "Skill",
    description: "Languages, frameworks, and tools. iconKey maps to Simple Icons slugs.",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      {
        name: "category",
        label: "Category",
        type: "select",
        options: SKILL_CATEGORIES.map((value) => ({
          value,
          label: value[0].toUpperCase() + value.slice(1),
        })),
      },
      {
        name: "level",
        label: "Level",
        type: "select",
        options: SKILL_LEVELS.map((value) => ({
          value,
          label: value[0].toUpperCase() + value.slice(1),
        })),
      },
      {
        name: "iconKey",
        label: "Simple Icons slug",
        type: "text",
        placeholder: "react, nodedotjs, mongodb, nextdotjs",
      },
      ...commonToggles,
    ],
  },
};
